### ISSUE TITLE
Add a permissive license

### ISSUE THREAD

**Issue by reefdog** [mattdaly/Fountain.js#15]
@mattdaly Do you have plans to add a permissive license so this can be safely used and extended? No judgement if not, just curious if I am able to safely build on Fountain.js or if I should write my own from scratch for a similar purpose.

**Comment by superlou** [comment]
Also interested in this.

**Comment by mattdaly** [comment]
A license has been added @superlou @reefdog

**Comment by superlou** [comment]
Much appreciated.  Thanks!

**Comment by reefdog** [comment]
Super, thanks @mattdaly!
